### ISSUE TITLE
DOC: Add link to paper on doc landing page

### ISSUE THREAD

**Issue by GaelVaroquaux** [soda-inria/carte#11]
Hi there,

I wanted to add a link to the paper on the doc landing page, but I wasn't sure if the index.html was generated or not. I can do the modifications, I just need to know which file to modify.

Thanks!

**Comment by gaetanbrison** [comment]
Documentation Update - Reference and xArchv Badge

Hi Gaël,

I’ve added a reference to the paper, but I’m not sure if it’s in the format you prefer.
If you’d like to modify it yourself, I’m working on a separate branch: **"gh-page3"** for the documentation. You can find it here:
https://github.com/soda-inria/carte/blob/gh-page3/docs/index.html

To verify if the deployment went smoothly after any modifications, you can check it here:
[GitHub Pages Deployment](https://github.com/soda-inria/carte/deployments/github-pages)

Hope this helps :)

**Comment by GaelVaroquaux** [comment]
This is great. Could you add a link to the official accepted paper:
https://openreview.net/forum?id=9kArQnKLDp
and mention ICML instead of "arXiv preprint arXiv:2402.16785"

Thanks!!

Gaël
