### ISSUE TITLE
Table2GraphTransformer may skip numerical feature normalization

### ISSUE THREAD

**Issue by AlexandreAbraham** [soda-inria/carte#12]
A series of changes and bad circumstances makes it that numerical columns with capitalized names are never transformed by PowerTransform as expected. This leads numerical columns to not be preprocessed at all in dataset clear_corpus for example.

Before this bug, which was introduced in commit ffea291, the preprocessing of numerical was done this way:
* In fit, PowerTransform was declared but not fit
* In transform, the function `_transform_numerical` was called which fitted the PowerTransformer.
This was not ideal, but working.

Here is the current process and why it fails. First, in the fit :
* the attribute `self.num_col_names` is set with names of numerical columns lowercased. The name `Column` is saved as `column`. See [here](https://github.com/soda-inria/carte/blob/7662b081085da60a13f6fcfde5ac0e2b320cba5d/carte_ai/src/carte_table_to_graph.py#L135)
* Then PowerTransformer is instantiated
* PowerTransformer is fitted on columns which names exists in `X.columns`. However, the names used are the ones in `self.num_col_names`. If any name has been lowercased, it therefore not exists in the original dataframe. See [here](https://github.com/soda-inria/carte/blob/7662b081085da60a13f6fcfde5ac0e2b320cba5d/carte_ai/src/carte_table_to_graph.py#L146). The consequence if that PowerTransformer is only fit on numerical columns with lowercase.

Then, in the transform, the same problem happens :
* The numerical columns are searched again (this is not a best practice I would say but this is another issue)
* The numerical features are isolated in a df called `X_numerical` and their name are lowercased. See [here](https://github.com/soda-inria/carte/blob/7662b081085da60a13f6fcfde5ac0e2b320cba5d/carte_ai/src/carte_table_to_graph.py#L180)
* Then, once again, the preprocessor is applied on columns that exist in the original df `X.columns` instead of  `X_numerical` where the names are lowercased. It therefore calls the transform operation on columns that are originally lowercased. See [here](https://github.com/soda-inria/carte/blob/7662b081085da60a13f6fcfde5ac0e2b320cba5d/carte_ai/src/carte_table_to_graph.py#L190)

For a simple debug:
* Add print statements in fit / transform
* Call a train on clear_corpus dataset
You will see that nothing is ever printed, indicating that PowerTransformer is never called.

**Comment by AlexandreAbraham** [comment]
By the way, I have run the most simple benchmark proposed in the readme using this cmd:
```
python carte_ai/scripts/evaluate_singletable.py -dn "clear_corpus" -nt "128" -m "reduced" -rs "1" -b "False" -dv "cpu"
```
And then I display the results of carte using:
```
 cat  carte_ai/results/singletable/clear_corpus/clear_corpus_carte-gnn_num_train-128_rs-1.csv
```

Before fixing category normalization  (numerical columns **are not** normalized):
```
carte-gnn_r2,carte-gnn_rmse
0.3991515185363349,0.8013108698966305
```

After fixing category normalization  (numerical columns **are** normalized):
```
carte-gnn_r2,carte-gnn_rmse
0.4302748437548505,0.7802813886107973
```

**Comment by gaetanbrison** [comment]
Hi @AlexandreAbraham,
I will have a look into it and come back to you 
Thanks for sharing

**Comment by gaetanbrison** [comment]
Hi,

Thank you once again for your feedback.
We have implemented the fix, and in this new version, the results are slightly better than the benchmark due to some slight change compared to original version

On our CPU server, here are some examples:

**clear_corpus**
```
python carte_ai/scripts/evaluate_singletable.py -dn "clear_corpus" -nt "128" -m "reduced" -rs "1" -b "False" -dv "cpu"
carte-gnn_r2,carte-gnn_rmse
0.46147214407741277,0.7586171147702063
```

**anime_planet**
```
python carte_ai/scripts/evaluate_singletable.py -dn "anime_planet" -nt "128" -m "reduced" -rs "1" -b "False" -dv "cpu"
carte-gnn_r2,carte-gnn_rmse
0.3683439589520078,0.695455215504306
```
...

Additionally, we plan to clean up the contribution guidelines and set up proper pre-commit checks before January 1, 2025, as we believe community contributions will be highly beneficial.

Best,
Gaëtan
